version: '3'
services:
  client:
    image: zacken1999/apiclientimage:1.0
    container_name: apiclient
    ports:
      - 5000:5000
    environment:
      - TOKEN_PATH=http://authserver:5001/token
      - RES_PATH=http://apiserver:8000/
      - VERIFY_TOKEN_PATH=http://authserver:5001/user
  authserver:
    image: zacken1999/authserverimage:1.0
    container_name: authserver
    ports:
      - 5001:5001
  apiserver:
    image: zacken1999/apiserverimage:1.0
    container_name: apiserver
    ports:
      - 8000:8000
    environment:
      - VERIFY_TOKEN_PATH=http://authserver:5001/user